name: Unit tests

on:
  push:
    paths:
      - '**.go'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0
      - name: Go mod verify
        run: go mod verify
      - name: Run unit tests
        run: go test -v -cover ./...
